'use strict';
const STORE='pazaryeri-live-v1', FOUR_HOURS=4*60*60*1000;
const $=id=>document.getElementById(id);let products=[],busy=false,lastRun=0;
const money=x=>x==null?'—':new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(x);
function number(v){if(v==null||String(v).trim()==='')return null;let s=String(v).trim().replace(/\s|₺|TRY|TL/gi,'');if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)&&n>=0?n:null}
function safeUrl(s){try{const u=new URL(s);return u.protocol==='https:'&&['trendyol.com','www.trendyol.com'].includes(u.hostname)?u.toString():''}catch{return ''}}
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseCSV(text){text=text.replace(/^\ufeff/,'');const first=text.split(/\r?\n/)[0]||'',d=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===d){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));cell='';if(row.some(Boolean))rows.push(row);row=[]}else cell+=c}if(quoted)throw Error('CSV tırnakları kapatılmamış');row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);return rows}
function save(){try{localStorage.setItem(STORE,JSON.stringify(products))}catch{setState('Tarayıcı depolaması dolu; rapor indir.',true)}}
function setState(text,error=false){$('state').textContent=text;$('state').className=error?'bad':'good'}
function download(filename,rows){const text='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function render(){let compared=products.filter(p=>p.price!=null),high=compared.filter(p=>p.own>p.price);$('total').textContent=products.length;$('priced').textContent=compared.length;$('high').textContent=high.length;$('failed').textContent=products.filter(p=>p.error).length;$('rows').innerHTML=products.map((p,i)=>{const delta=p.price==null?null:p.own-p.price,percent=delta!=null&&p.price>0?100*delta/p.price:null;const diff=delta==null?'—':`${delta>0?'+':''}${money(delta)} / ${percent==null?'—':percent.toFixed(1)+'%'}`;return `<tr><td><strong>${escapeHtml(p.name)}</strong><br><small>${escapeHtml(p.barcode)}</small></td><td>${money(p.own)}</td><td>${money(p.price)}</td><td class="${delta!=null&&delta>0?'bad':'good'}">${diff}</td><td><input aria-label="Trendyol URL ${escapeHtml(p.barcode)}" data-url="${i}" value="${escapeHtml(p.url)}" placeholder="https://www.trendyol.com/..."></td><td>${p.checkedAt?new Date(p.checkedAt).toLocaleString('tr-TR'):'—'}</td><td class="${p.error?'bad':'muted'}">${escapeHtml(p.error|| (p.checkedAt?'Fiyat kaydedildi':'Kontrol edilmedi'))}</td><td><button data-check="${i}">Sorgula</button> <button class="secondary" data-history="${i}">Geçmiş</button></td></tr>`}).join('')||'<tr><td colspan="8">Henüz ürün yok. CSV yükle.</td></tr>'}
async function check(p){if(!p.url){p.error='Trendyol ürün bağlantısı eksik.';render();return 'missing'};try{const response=await fetch('/api/price',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:p.url})});let result;try{result=await response.json()}catch{throw Error('Sunucu JSON yanıtı vermedi.')}if(!response.ok)throw Object.assign(Error(result.error||'Fiyat sorgusu başarısız.'),{status:response.status,origin:result.status});if(!Number.isFinite(result.price)||result.price<=0)throw Error('Geçerli fiyat bulunamadı.');if(result.sku&&p.barcode&&result.sku!==p.barcode){p.error=`Barkod uyuşmuyor: sayfa ${result.sku}, ürün ${p.barcode}. Fiyat kaydedilmedi.`;return 'mismatch'};p.price=result.price;p.checkedAt=result.checkedAt;p.error='';p.history.push({price:result.price,at:result.checkedAt,source:result.source,name:result.name});p.history=p.history.slice(-200);return 'ok'}catch(err){p.error=err.message||'Bilinmeyen hata';return err.origin===403||err.origin===429?'blocked':'error'}finally{save();render()}}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function all(){if(busy)return;busy=true;$('checkAll').disabled=true;try{const targets=products.filter(p=>p.url);if(!targets.length){setState('Kontrol edilecek doğrulanmış ürün bağlantısı yok.',true);return}let success=0;for(let i=0;i<targets.length;i++){setState(`${i+1}/${targets.length} sorgulanıyor · ${success} başarılı`);const result=await check(targets[i]);if(result==='ok')success++;if(result==='blocked'){setState(`Kaynak erişimi reddetti. ${success}/${targets.length} fiyat güncellendi.`,true);return}if(i<targets.length-1)await sleep(3000)}lastRun=Date.now();setState(`${success}/${targets.length} fiyat başarıyla alındı. Başarısız ürünlerin durumuna bak.`,success!==targets.length)}finally{busy=false;$('checkAll').disabled=false}}
$('file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5_000_000)throw Error('Dosya en fazla 5 MB olmalı.');const rows=parseCSV(await f.text());const head=rows.shift().map(x=>x.trim().toLocaleLowerCase('tr-TR').replace(/\s+/g,'_'));const idx=k=>head.indexOf(k),required=['barkod','urun_adi','idefix_fiyat'];if(required.some(k=>idx(k)<0))throw Error('Gerekli CSV başlıkları eksik: '+required.join(', '));let count=0;for(const row of rows){const barcode=String(row[idx('barkod')]||'').trim(),name=String(row[idx('urun_adi')]||'').trim(),own=number(row[idx('idefix_fiyat')]);if(!barcode||!name||own==null)continue;const old=products.find(p=>p.barcode===barcode),url=safeUrl(row[idx('trendyol_url')]||'')||old?.url||'';if(old){old.name=name;old.own=own;old.url=url}else products.push({barcode,name,own,url,price:null,checkedAt:null,error:'',history:[]});count++}save();render();setState(`${count} ürün işlendi. URL'si olanları kontrol edebilirsin.`)}catch(error){setState('CSV hatası: '+error.message,true)}finally{e.target.value=''}});
$('rows').addEventListener('change',e=>{const i=Number(e.target.dataset.url);if(!Number.isInteger(i)||!products[i])return;const raw=e.target.value.trim(),url=safeUrl(raw);if(raw&&!url){setState('Yalnızca geçerli Trendyol HTTPS bağlantısı gir.',true);render();return}if(products[i].url!==url){products[i].url=url;products[i].price=null;products[i].checkedAt=null;products[i].history=[];products[i].error='Yeni bağlantı: eşleşmeyi doğrulayıp sorgula.'}save();render()});
$('rows').addEventListener('click',async e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.check!=null){if(busy)return;const i=Number(btn.dataset.check),p=products[i];if(!p)return;busy=true;$('checkAll').disabled=true;setState('Ürün sorgulanıyor...');try{const result=await check(p);setState(result==='ok'?'Gerçek fiyat okundu.':p.error,result!=='ok')}finally{busy=false;$('checkAll').disabled=false}}else if(btn.dataset.history!=null){const p=products[Number(btn.dataset.history)];$('history').replaceChildren();const title=document.createElement('h3');title.textContent=p.name+' — '+p.barcode;$('history').append(title);for(const h of [...p.history].reverse()){const line=document.createElement('p');line.textContent=`${new Date(h.at).toLocaleString('tr-TR')} · ${money(h.price)} · ${h.source||''}`;$('history').append(line)}if(!p.history.length)$('history').append(document.createTextNode('Henüz fiyat geçmişi yok.'))}});
$('checkAll').addEventListener('click',all);$('template').addEventListener('click',()=>download('idefix-sablon.csv',[['barkod','urun_adi','idefix_fiyat','trendyol_url'],['8690000000000','Örnek ürün',1499,'']]));$('export').addEventListener('click',()=>download('fiyat-analiz.csv',[['barkod','urun_adi','idefix_fiyat','trendyol_fiyat','fark_tl','fark_yuzde','trendyol_url','son_basari','hata'],...products.map(p=>[p.barcode,p.name,p.own,p.price,p.price==null?'':p.own-p.price,p.price>0?(p.own-p.price)/p.price*100:'',p.url,p.checkedAt,p.error])]));
try{const stored=JSON.parse(localStorage.getItem(STORE)||'[]');if(Array.isArray(stored))products=stored.filter(p=>p&&typeof p.barcode==='string'&&Array.isArray(p.history)).slice(0,5000)}catch{products=[]}render();setInterval(()=>{if(!$('auto').checked||busy||!products.some(p=>p.url))return;if(Date.now()-lastRun>=FOUR_HOURS)all()},60_000);
